import Hero from "@/app/components/Hero";
import HologramSection from "@/app/components/hologramsection";
import NeuralLink from "@/app/components/neurallink";
import GroqLPU from "@/app/components/groqlpu";
import OperatorConsoleSection from "@/app/components/operatorconsolesection";
import MicroTaskEngine from "@/app/components/microtaskengine";
import FileAnalyzer from "@/app/components/fileanalyzer";
import WorkflowBuilder from "@/app/components/workflowbuilder";
import PoweredByGroq from "@/app/components/poweredbygroq";
import CoachingPost from "@/app/components/coachingpost";
import FinalCTA from "@
